### ISSUE TITLE
mystery problem- Jenkins is choking on this resource

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/source-reeflifesurvey#1]
I think. it has been working on dwc2parquet for 40 minutes...

**Comment by jhpoelen** [comment]
Thanks for letting me know about this!

It turns out that Jenkins was patiently waiting in line for the parquet conversion job to run. For detailed logging see: http://archive.effechecka.org/job/reeflifesurvey/3/console .

The reason why this was taking so long? See https://github.com/gimmefreshdata/freshdata/issues/44 .

So, it seems that the jenkins jobs are pretty patient and . . . I'll have a look at the root cause.
